Repository cleanlab/cleanlab, pull requests merged in 2024-03, with the labels that each got.

#1038 Update version for 2.6.1 release
  cleanlab/version.py
  docs/source/conf.py
Labels: trivial-change

#1045 Convert DataFrame features to numpy arrays in null value check
  cleanlab/datalab/internal/issue_manager/null.py
  tests/datalab/datalab/end_to_end_tests/__init__.py
  tests/datalab/datalab/end_to_end_tests/issue_types/__init__.py
  tests/datalab/datalab/end_to_end_tests/issue_types/test_null.py
Labels: trivial-change, usability-improvement

#1057 Add warning message about TensorFlow compatibility to docs
  cleanlab/models/keras.py
Labels: trivial-change, documentation

#1061 Bump version to 2.6.4 for development version
  cleanlab/version.py
Labels: trivial-change

#1062 Update .coveragerc to omit specific experimental files for code coverage
  .coveragerc
Labels: tooling

#1064 Optimize segmentation/rank.py for performance and maintainability
  cleanlab/segmentation/rank.py
Labels: code improvement, performance
